"""Merge NGSL-Spoken 1.2 (rank + English definition) with the hand-written Vietnamese glosses
and examples into words.js, failing loudly on any gap so a missing or misspelled word never
ships silently."""
import csv, json, re, sys

TRANSCRIPTION_LABELS = {"laughter", "unclear", "pause"}

def ranked_words():
    rows = list(csv.DictReader(open("ngsl-spoken-1.2-stats.csv")))
    words = [(r["Lemma"], r["Rank"]) for r in rows if r["Lemma"].lower() not in TRANSCRIPTION_LABELS]
    # "true" was mangled into a boolean by a spreadsheet and lost its rank; it goes last.
    known = sorted([(w, int(r)) for w, r in words if r.isdigit()], key=lambda x: x[1])
    unranked = [w.lower() for w, r in words if not r.isdigit()]
    return [w for w, _ in known] + unranked

def definitions():
    return {r["Word"].strip().lower(): r["Definition"].strip() for r in csv.DictReader(open("ngsl-spoken-1.2-definitions.csv"))}

def glosses():
    out, errors = {}, []
    for n, line in enumerate(open("words-vi.txt", encoding="utf-8"), 1):
        parts = [p.strip() for p in line.rstrip("\n").split(" | ")]
        if len(parts) != 3:
            errors.append(f"line {n}: expected 3 fields, got {len(parts)}")
            continue
        word, vi, example = parts
        if not re.search(r"\{[^}]+\}", example):
            errors.append(f"line {n} ({word}): example has no {{blank}}")
        if word.lower() in out:
            errors.append(f"line {n}: duplicate '{word}'")
        out[word.lower()] = (vi, example)
    return out, errors

ranked = ranked_words()
defs = definitions()
gl, errors = glosses()
missing = [w for w in ranked if w.lower() not in gl]
extra = sorted(set(gl) - {w.lower() for w in ranked})
errors += [f"no gloss for '{w}'" for w in missing] + [f"gloss for unlisted word '{w}'" for w in extra]
if errors:
    sys.exit("\n".join(errors))

entries = [[w, gl[w.lower()][0], gl[w.lower()][1], defs.get(w.lower(), "")] for w in ranked]
no_def = [e[0] for e in entries if not e[3]]
with open("words.js", "w", encoding="utf-8") as f:
    f.write("// Generated by data/build_words.py — edit words-vi.txt, not this file.\n")
    f.write("// Word list and English definitions: NGSL-Spoken 1.2, CC BY-SA 4.0, newgeneralservicelist.com\n")
    f.write("window.WORDS = [\n" + ",\n".join(json.dumps(e, ensure_ascii=False) for e in entries) + "\n];\n")
print(f"{len(entries)} words written; {len(no_def)} without an NGSL definition: {no_def}")
